#!/bin/sh

printf 'y'| sudo apt remove 0trace
printf 'y'| sudo apt remove aesfix
printf 'y'| sudo apt remove aeskeyfind
printf 'y'| sudo apt remove afflib
printf 'y'| sudo apt remove aflplusplus
printf 'y'| sudo apt remove aircrack-ng
printf 'y'| sudo apt remove airgeddon
printf 'y'| sudo apt remove all-tools
printf 'y'| sudo apt remove altdns
printf 'y'| sudo apt remove amap
printf 'y'| sudo apt remove amass
printf 'y'| sudo apt remove android-sdk-meta
printf 'y'| sudo apt remove apache-users
printf 'y'| sudo apt remove apache2
printf 'y'| sudo apt remove apktool
printf 'y'| sudo apt remove apple-bleee
printf 'y'| sudo apt remove arjun
printf 'y'| sudo apt remove armitage
printf 'y'| sudo apt remove arp-scan
printf 'y'| sudo apt remove arping
printf 'y'| sudo apt remove arpwatch
printf 'y'| sudo apt remove asleap
printf 'y'| sudo apt remove assetfinder
printf 'y'| sudo apt remove atftp
printf 'y'| sudo apt remove autopsy
printf 'y'| sudo apt remove axel
printf 'y'| sudo apt remove b374k
printf 'y'| sudo apt remove backdoor-factory
printf 'y'| sudo apt remove bed
printf 'y'| sudo apt remove beef-xss
printf 'y'| sudo apt remove berate-ap
printf 'y'| sudo apt remove bettercap
printf 'y'| sudo apt remove bettercap-ui
printf 'y'| sudo apt remove bind9
printf 'y'| sudo apt remove bing-ip2hosts
printf 'y'| sudo apt remove binwalk
printf 'y'| sudo apt remove bloodhound
printf 'y'| sudo apt remove bloodhound.py
printf 'y'| sudo apt remove bluelog
printf 'y'| sudo apt remove blueranger
printf 'y'| sudo apt remove bluesnarfer
printf 'y'| sudo apt remove bluez
printf 'y'| sudo apt remove braa
printf 'y'| sudo apt remove bruteforce-luks
printf 'y'| sudo apt remove bruteforce-salted-openssl
printf 'y'| sudo apt remove bruteforce-wallet
printf 'y'| sudo apt remove bruteshark
printf 'y'| sudo apt remove brutespray
printf 'y'| sudo apt remove btscanner
printf 'y'| sudo apt remove bulk-extractor
printf 'y'| sudo apt remove bully
printf 'y'| sudo apt remove burpsuite
printf 'y'| sudo apt remove bytecode-viewer
printf 'y'| sudo apt remove cabextract
printf 'y'| sudo apt remove cadaver
printf 'y'| sudo apt remove caldera
printf 'y'| sudo apt remove calico
printf 'y'| sudo apt remove capstone
printf 'y'| sudo apt remove ccrypt
printf 'y'| sudo apt remove certgraph
printf 'y'| sudo apt remove certipy-ad
printf 'y'| sudo apt remove cewl
printf 'y'| sudo apt remove changeme
printf 'y'| sudo apt remove chaosreader
printf 'y'| sudo apt remove cherrytree
printf 'y'| sudo apt remove chirp
printf 'y'| sudo apt remove chisel
printf 'y'| sudo apt remove chkrootkit
printf 'y'| sudo apt remove chntpw
printf 'y'| sudo apt remove chromium
printf 'y'| sudo apt remove cifs-utils
printf 'y'| sudo apt remove cilium-cli
printf 'y'| sudo apt remove cisco-auditing-tool
printf 'y'| sudo apt remove cisco-global-exploiter
printf 'y'| sudo apt remove cisco-ocs
printf 'y'| sudo apt remove cisco-torch
printf 'y'| sudo apt remove cisco7crack
printf 'y'| sudo apt remove clamav
printf 'y'| sudo apt remove cloud-enum
printf 'y'| sudo apt remove cloudbrute
printf 'y'| sudo apt remove cmospwd
printf 'y'| sudo apt remove cmseek
printf 'y'| sudo apt remove cntlm
printf 'y'| sudo apt remove code-oss
printf 'y'| sudo apt remove colly
printf 'y'| sudo apt remove command-not-found
printf 'y'| sudo apt remove commix
printf 'y'| sudo apt remove copy-router-config
printf 'y'| sudo apt remove cosign
printf 'y'| sudo apt remove covenant-kbx
printf 'y'| sudo apt remove cowpatty
printf 'y'| sudo apt remove crack
printf 'y'| sudo apt remove crackle
printf 'y'| sudo apt remove crackmapexec
printf 'y'| sudo apt remove creddump7
printf 'y'| sudo apt remove cri-tools
printf 'y'| sudo apt remove crowbar
printf 'y'| sudo apt remove crunch
printf 'y'| sudo apt remove cryptcat
printf 'y'| sudo apt remove cryptsetup
printf 'y'| sudo apt remove cryptsetup-nuke-password
printf 'y'| sudo apt remove cupid-wpa
printf 'y'| sudo apt remove curl
printf 'y'| sudo apt remove curlftpfs
printf 'y'| sudo apt remove cutecom
printf 'y'| sudo apt remove cutycapt
printf 'y'| sudo apt remove cymothoa
printf 'y'| sudo apt remove darkstat
printf 'y'| sudo apt remove davtest
printf 'y'| sudo apt remove dbd
printf 'y'| sudo apt remove dbeaver
printf 'y'| sudo apt remove dc3dd
printf 'y'| sudo apt remove dcfldd
printf 'y'| sudo apt remove ddrescue
printf 'y'| sudo apt remove de4dot
printf 'y'| sudo apt remove defectdojo
printf 'y'| sudo apt remove dex2jar
printf 'y'| sudo apt remove dfdatetime
printf 'y'| sudo apt remove dfvfs
printf 'y'| sudo apt remove dfwinreg
printf 'y'| sudo apt remove dhcpig
printf 'y'| sudo apt remove dirb
printf 'y'| sudo apt remove dirbuster
printf 'y'| sudo apt remove dirsearch
printf 'y'| sudo apt remove dislocker
printf 'y'| sudo apt remove distorm3
printf 'y'| sudo apt remove dmitry
printf 'y'| sudo apt remove dns2tcp
printf 'y'| sudo apt remove dnscat2
printf 'y'| sudo apt remove dnschef
printf 'y'| sudo apt remove dnsenum
printf 'y'| sudo apt remove dnsgen
printf 'y'| sudo apt remove dnsmap
printf 'y'| sudo apt remove dnsrecon
printf 'y'| sudo apt remove dnstracer
printf 'y'| sudo apt remove dnstwist
printf 'y'| sudo apt remove dnswalk
printf 'y'| sudo apt remove dnsx
printf 'y'| sudo apt remove doona
printf 'y'| sudo apt remove dos2unix
printf 'y'| sudo apt remove dotdotpwn
printf 'y'| sudo apt remove dradis
printf 'y'| sudo apt remove driftnet
printf 'y'| sudo apt remove dscan
printf 'y'| sudo apt remove dsniff
printf 'y'| sudo apt remove dufflebag
printf 'y'| sudo apt remove dumpsterdiver
printf 'y'| sudo apt remove dumpzilla
printf 'y'| sudo apt remove dvwa
printf 'y'| sudo apt remove dwarf2json
printf 'y'| sudo apt remove eaphammer
printf 'y'| sudo apt remove eapmd5pass
printf 'y'| sudo apt remove edb-debugger
printf 'y'| sudo apt remove eksctl
printf 'y'| sudo apt remove email2phonenumber
printf 'y'| sudo apt remove emailharvester
printf 'y'| sudo apt remove enum4linux
printf 'y'| sudo apt remove enum4linux-ng
printf 'y'| sudo apt remove enumiax
printf 'y'| sudo apt remove ethtool
printf 'y'| sudo apt remove ettercap
printf 'y'| sudo apt remove evil-ssdp
printf 'y'| sudo apt remove evil-winrm
printf 'y'| sudo apt remove evilginx2
printf 'y'| sudo apt remove exe2hexbat
printf 'y'| sudo apt remove exiflooter
printf 'y'| sudo apt remove exifprobe
printf 'y'| sudo apt remove exiv2
printf 'y'| sudo apt remove expect
printf 'y'| sudo apt remove exploitdb
printf 'y'| sudo apt remove exploitdb-bin-sploits
printf 'y'| sudo apt remove exploitdb-papers
printf 'y'| sudo apt remove ext3grep
printf 'y'| sudo apt remove ext4magic
printf 'y'| sudo apt remove extundelete
printf 'y'| sudo apt remove eyewitness
printf 'y'| sudo apt remove faraday-agent-dispatcher
printf 'y'| sudo apt remove faraday-cli
printf 'y'| sudo apt remove fatcat
printf 'y'| sudo apt remove fcrackzip
printf 'y'| sudo apt remove fern-wifi-cracker
printf 'y'| sudo apt remove feroxbuster
printf 'y'| sudo apt remove ferret-sidejack
printf 'y'| sudo apt remove ffuf
printf 'y'| sudo apt remove fierce
printf 'y'| sudo apt remove fiked
printf 'y'| sudo apt remove finalrecon
printf 'y'| sudo apt remove firefox-developer-edition-kbx
printf 'y'| sudo apt remove firewalk
printf 'y'| sudo apt remove firmware-mod-kit
printf 'y'| sudo apt remove flashrom
printf 'y'| sudo apt remove foremost
printf 'y'| sudo apt remove forensic-artifacts
printf 'y'| sudo apt remove forensics-colorize
printf 'y'| sudo apt remove fping
printf 'y'| sudo apt remove fragrouter
printf 'y'| sudo apt remove framework2
printf 'y'| sudo apt remove freeradius
printf 'y'| sudo apt remove freeradius-wpe
printf 'y'| sudo apt remove freerdp2
printf 'y'| sudo apt remove ftester
printf 'y'| sudo apt remove fuse3
printf 'y'| sudo apt remove fwbuilder
printf 'y'| sudo apt remove galleta
printf 'y'| sudo apt remove gdb-peda
printf 'y'| sudo apt remove gdisk
printf 'y'| sudo apt remove getallurls
printf 'y'| sudo apt remove ghidra
printf 'y'| sudo apt remove git
printf 'y'| sudo apt remove gitleaks
printf 'y'| sudo apt remove glibc
printf 'y'| sudo apt remove gnuradio
printf 'y'| sudo apt remove gobuster
printf 'y'| sudo apt remove godoh
printf 'y'| sudo apt remove golang-github-binject-go-donut
printf 'y'| sudo apt remove goldeneye
printf 'y'| sudo apt remove goofile
printf 'y'| sudo apt remove google-nexus-tools
printf 'y'| sudo apt remove gophish
printf 'y'| sudo apt remove gospider
printf 'y'| sudo apt remove gpart
printf 'y'| sudo apt remove gparted
printf 'y'| sudo apt remove gpp-decrypt
printf 'y'| sudo apt remove gqrx-sdr
printf 'y'| sudo apt remove gr-air-modes
printf 'y'| sudo apt remove gr-iqbal
printf 'y'| sudo apt remove gr-osmosdr
printf 'y'| sudo apt remove grokevt
printf 'y'| sudo apt remove gss-ntlmssp
printf 'y'| sudo apt remove gtkhash
printf 'y'| sudo apt remove guymager
printf 'y'| sudo apt remove gvm
printf 'y'| sudo apt remove h8mail
printf 'y'| sudo apt remove hackrf
printf 'y'| sudo apt remove hak5-wifi-coconut
printf 'y'| sudo apt remove hakrawler
printf 'y'| sudo apt remove hamster-sidejack
printf 'y'| sudo apt remove hash-identifier
printf 'y'| sudo apt remove hashcat
printf 'y'| sudo apt remove hashcat-utils
printf 'y'| sudo apt remove hashdeep
printf 'y'| sudo apt remove hashid
printf 'y'| sudo apt remove hashrat
printf 'y'| sudo apt remove havoc
printf 'y'| sudo apt remove hb-honeypot
printf 'y'| sudo apt remove hcxtools
printf 'y'| sudo apt remove heartleech
printf 'y'| sudo apt remove hexinject
printf 'y'| sudo apt remove hivex
printf 'y'| sudo apt remove hostapd-mana
printf 'y'| sudo apt remove hostapd-wpe
printf 'y'| sudo apt remove hosthunter
printf 'y'| sudo apt remove hostsman
printf 'y'| sudo apt remove hotpatch
printf 'y'| sudo apt remove hping3
printf 'y'| sudo apt remove htshells
printf 'y'| sudo apt remove httprint
printf 'y'| sudo apt remove httprobe
printf 'y'| sudo apt remove httpx-toolkit
printf 'y'| sudo apt remove httrack
printf 'y'| sudo apt remove hubble
printf 'y'| sudo apt remove humble
printf 'y'| sudo apt remove hurl
printf 'y'| sudo apt remove hydra
printf 'y'| sudo apt remove hyperion
printf 'y'| sudo apt remove i2c-tools
printf 'y'| sudo apt remove iaxflood
printf 'y'| sudo apt remove ibombshell
printf 'y'| sudo apt remove ident-user-enum
printf 'y'| sudo apt remove ifenslave
printf 'y'| sudo apt remove ike-scan
printf 'y'| sudo apt remove imhex
printf 'y'| sudo apt remove impacket
printf 'y'| sudo apt remove impacket-scripts
printf 'y'| sudo apt remove inetsim
printf 'y'| sudo apt remove inspectrum
printf 'y'| sudo apt remove inspy
printf 'y'| sudo apt remove instaloader
printf 'y'| sudo apt remove intrace
printf 'y'| sudo apt remove inviteflood
printf 'y'| sudo apt remove iodine
printf 'y'| sudo apt remove ipv6toolkit
printf 'y'| sudo apt remove irpas
printf 'y'| sudo apt remove ismtp
printf 'y'| sudo apt remove isr-evilgrade
printf 'y'| sudo apt remove ivre
printf 'y'| sudo apt remove iw
printf 'y'| sudo apt remove jadx
printf 'y'| sudo apt remove javasnoop
printf 'y'| sudo apt remove jboss-autopwn
printf 'y'| sudo apt remove jd-gui
printf 'y'| sudo apt remove john
printf 'y'| sudo apt remove johnny
printf 'y'| sudo apt remove joomscan
printf 'y'| sudo apt remove joplin
printf 'y'| sudo apt remove jsp-file-browser
printf 'y'| sudo apt remove jsql
printf 'y'| sudo apt remove juice-shop
printf 'y'| sudo apt remove kali-autopilot
printf 'y'| sudo apt remove kali-community-wallpapers
printf 'y'| sudo apt remove kali-defaults
printf 'y'| sudo apt remove kali-meta
printf 'y'| sudo apt remove kali-tweaks
printf 'y'| sudo apt remove kali-wallpapers
printf 'y'| sudo apt remove kalibrate-rtl
printf 'y'| sudo apt remove kerberoast
printf 'y'| sudo apt remove kismet
printf 'y'| sudo apt remove knocker
printf 'y'| sudo apt remove koadic
printf 'y'| sudo apt remove kubernetes-helm
printf 'y'| sudo apt remove kustomize
printf 'y'| sudo apt remove lapsdumper
printf 'y'| sudo apt remove laudanum
printf 'y'| sudo apt remove lbd
printf 'y'| sudo apt remove legion
printf 'y'| sudo apt remove libewf
printf 'y'| sudo apt remove libfindrtp
printf 'y'| sudo apt remove libfreefare
printf 'y'| sudo apt remove libimage-exiftool-perl
printf 'y'| sudo apt remove libnfc
printf 'y'| sudo apt remove libpst
printf 'y'| sudo apt remove libsmali-java
printf 'y'| sudo apt remove linux-exploit-suggester
printf 'y'| sudo apt remove llvm-defaults
printf 'y'| sudo apt remove lvm2
printf 'y'| sudo apt remove lynis
printf 'y'| sudo apt remove mac-robber
printf 'y'| sudo apt remove macchanger
printf 'y'| sudo apt remove magicrescue
printf 'y'| sudo apt remove maltego-teeth
printf 'y'| sudo apt remove maryam
printf 'y'| sudo apt remove maskprocessor
printf 'y'| sudo apt remove masscan
printf 'y'| sudo apt remove massdns
printf 'y'| sudo apt remove mc
printf 'y'| sudo apt remove mdbtools
printf 'y'| sudo apt remove mdk3
printf 'y'| sudo apt remove mdk4
printf 'y'| sudo apt remove medusa
printf 'y'| sudo apt remove memdump
printf 'y'| sudo apt remove mercurial
printf 'y'| sudo apt remove merlin
printf 'y'| sudo apt remove merlin-agent
printf 'y'| sudo apt remove metacam
printf 'y'| sudo apt remove metagoofil
printf 'y'| sudo apt remove metasploit-framework
printf 'y'| sudo apt remove mfcuk
printf 'y'| sudo apt remove mfoc
printf 'y'| sudo apt remove mfterm
printf 'y'| sudo apt remove mimikatz
printf 'y'| sudo apt remove minicom
printf 'y'| sudo apt remove miredo
printf 'y'| sudo apt remove missidentify
printf 'y'| sudo apt remove mitmproxy
printf 'y'| sudo apt remove mongo-tools
printf 'y'| sudo apt remove msfpc
printf 'y'| sudo apt remove multiforcer
printf 'y'| sudo apt remove multimac
printf 'y'| sudo apt remove multimon-ng
printf 'y'| sudo apt remove myrescue
printf 'y'| sudo apt remove mysql-defaults
printf 'y'| sudo apt remove naabu
printf 'y'| sudo apt remove name-that-hash
printf 'y'| sudo apt remove nasm
printf 'y'| sudo apt remove nasty
printf 'y'| sudo apt remove nbtscan
printf 'y'| sudo apt remove nbtscan-unixwiz
printf 'y'| sudo apt remove ncat-w32
printf 'y'| sudo apt remove ncrack
printf 'y'| sudo apt remove ncurses-hexedit
printf 'y'| sudo apt remove net-snmp
printf 'y'| sudo apt remove net-tools
printf 'y'| sudo apt remove netbase
printf 'y'| sudo apt remove netcat
printf 'y'| sudo apt remove netdiscover
printf 'y'| sudo apt remove netmask
printf 'y'| sudo apt remove netsed
printf 'y'| sudo apt remove netsniff-ng
printf 'y'| sudo apt remove netw-ib-ox-ag
printf 'y'| sudo apt remove nextnet
printf 'y'| sudo apt remove nfs-utils
printf 'y'| sudo apt remove ngrep
printf 'y'| sudo apt remove nikto
printf 'y'| sudo apt remove nipper-ng
printf 'y'| sudo apt remove nishang
printf 'y'| sudo apt remove nmap
printf 'y'| sudo apt remove nmapsi4
printf 'y'| sudo apt remove nuclei
printf 'y'| sudo apt remove o-saft
printf 'y'| sudo apt remove oclgausscrack
printf 'y'| sudo apt remove odat
printf 'y'| sudo apt remove offsec-courses
printf 'y'| sudo apt remove ohrwurm
printf 'y'| sudo apt remove ollydbg
printf 'y'| sudo apt remove onesixtyone
printf 'y'| sudo apt remove openocd
printf 'y'| sudo apt remove openssh
printf 'y'| sudo apt remove openvpn
printf 'y'| sudo apt remove ophcrack
printf 'y'| sudo apt remove oscanner
printf 'y'| sudo apt remove osrframework
printf 'y'| sudo apt remove outguess
printf 'y'| sudo apt remove owasp-mantra-ff
printf 'y'| sudo apt remove owl
printf 'y'| sudo apt remove p0f
printf 'y'| sudo apt remove p7zip
printf 'y'| sudo apt remove pack
printf 'y'| sudo apt remove pack2
printf 'y'| sudo apt remove pacu
printf 'y'| sudo apt remove padbuster
printf 'y'| sudo apt remove paros
printf 'y'| sudo apt remove parsero
printf 'y'| sudo apt remove parted
printf 'y'| sudo apt remove pasco
printf 'y'| sudo apt remove passdetective
printf 'y'| sudo apt remove passing-the-hash
printf 'y'| sudo apt remove patator
printf 'y'| sudo apt remove payloadsallthethings
printf 'y'| sudo apt remove pdf-parser
printf 'y'| sudo apt remove pdfcrack
printf 'y'| sudo apt remove pdfid
printf 'y'| sudo apt remove peass-ng
printf 'y'| sudo apt remove peirates
printf 'y'| sudo apt remove perl-cisco-copyconfig
printf 'y'| sudo apt remove pev
printf 'y'| sudo apt remove phishery
printf 'y'| sudo apt remove photon
printf 'y'| sudo apt remove php-defaults
printf 'y'| sudo apt remove phpggc
printf 'y'| sudo apt remove phpsploit
printf 'y'| sudo apt remove pipal
printf 'y'| sudo apt remove pixiewps
printf 'y'| sudo apt remove plaso
printf 'y'| sudo apt remove plocate
printf 'y'| sudo apt remove pnscan
printf 'y'| sudo apt remove pocsuite3
printf 'y'| sudo apt remove polenum
printf 'y'| sudo apt remove pompem
printf 'y'| sudo apt remove portspoof
printf 'y'| sudo apt remove poshc2
printf 'y'| sudo apt remove powercat
printf 'y'| sudo apt remove powershell
printf 'y'| sudo apt remove powershell-empire
printf 'y'| sudo apt remove powersploit
printf 'y'| sudo apt remove princeprocessor
printf 'y'| sudo apt remove protos-sip
printf 'y'| sudo apt remove proxify
printf 'y'| sudo apt remove proxmark3
printf 'y'| sudo apt remove proxychains-ng
printf 'y'| sudo apt remove proxytunnel
printf 'y'| sudo apt remove pskracker
printf 'y'| sudo apt remove ptunnel
printf 'y'| sudo apt remove pwnat
printf 'y'| sudo apt remove pwncat
printf 'y'| sudo apt remove python-defaults
printf 'y'| sudo apt remove python-faraday
printf 'y'| sudo apt remove python-ldapdomaindump
printf 'y'| sudo apt remove python-pip
printf 'y'| sudo apt remove python-virtualenv
printf 'y'| sudo apt remove qemu
printf 'y'| sudo apt remove qsslcaudit
printf 'y'| sudo apt remove quark-engine
printf 'y'| sudo apt remove radare2
printf 'y'| sudo apt remove rainbowcrack
printf 'y'| sudo apt remove rake
printf 'y'| sudo apt remove rarcrack
printf 'y'| sudo apt remove raven
printf 'y'| sudo apt remove rcracki-mt
printf 'y'| sudo apt remove rdesktop
printf 'y'| sudo apt remove reaver
printf 'y'| sudo apt remove rebind
printf 'y'| sudo apt remove recon-ng
printf 'y'| sudo apt remove reconspider
printf 'y'| sudo apt remove recordmydesktop
printf 'y'| sudo apt remove recoverdm
printf 'y'| sudo apt remove recoverjpeg
printf 'y'| sudo apt remove redeye
printf 'y'| sudo apt remove redfang
printf 'y'| sudo apt remove redsnarf
printf 'y'| sudo apt remove redsocks
printf 'y'| sudo apt remove reglookup
printf 'y'| sudo apt remove regripper
printf 'y'| sudo apt remove rekono-kbx
printf 'y'| sudo apt remove rephrase
printf 'y'| sudo apt remove requests
printf 'y'| sudo apt remove responder
printf 'y'| sudo apt remove rev-proxy-grapher
printf 'y'| sudo apt remove rfcat
printf 'y'| sudo apt remove rfdump
printf 'y'| sudo apt remove ridenum
printf 'y'| sudo apt remove rifiuti
printf 'y'| sudo apt remove rifiuti2
printf 'y'| sudo apt remove rizin-cutter
printf 'y'| sudo apt remove rkhunter
printf 'y'| sudo apt remove rling
printf 'y'| sudo apt remove robotstxt
printf 'y'| sudo apt remove ropper
printf 'y'| sudo apt remove routerkeygenpc
printf 'y'| sudo apt remove routersploit
printf 'y'| sudo apt remove rsakeyfind
printf 'y'| sudo apt remove rsmangler
printf 'y'| sudo apt remove rtlsdr-scanner
printf 'y'| sudo apt remove rtpbreak
printf 'y'| sudo apt remove rtpflood
printf 'y'| sudo apt remove rtpinsertsound
printf 'y'| sudo apt remove rtpmixsound
printf 'y'| sudo apt remove ruby-pedump
printf 'y'| sudo apt remove rz-ghidra
printf 'y'| sudo apt remove s3scanner
printf 'y'| sudo apt remove safecopy
printf 'y'| sudo apt remove sakis3g
printf 'y'| sudo apt remove samba
printf 'y'| sudo apt remove samdump2
printf 'y'| sudo apt remove sbd
printf 'y'| sudo apt remove scalpel
printf 'y'| sudo apt remove scapy
printf 'y'| sudo apt remove screen
printf 'y'| sudo apt remove scrounge-ntfs
printf 'y'| sudo apt remove sctpscan
printf 'y'| sudo apt remove seclists
printf 'y'| sudo apt remove secure-socket-funneling
printf 'y'| sudo apt remove sendemail
printf 'y'| sudo apt remove sentrypeer
printf 'y'| sudo apt remove set
printf 'y'| sudo apt remove sfuzz
printf 'y'| sudo apt remove shed
printf 'y'| sudo apt remove shellfire
printf 'y'| sudo apt remove shellnoob
printf 'y'| sudo apt remove shellter
printf 'y'| sudo apt remove sherlock
printf 'y'| sudo apt remove sidguesser
printf 'y'| sudo apt remove siege
printf 'y'| sudo apt remove sigma-cli
printf 'y'| sudo apt remove silenttrinity
printf 'y'| sudo apt remove siparmyknife
printf 'y'| sudo apt remove sipcrack
printf 'y'| sudo apt remove sipp
printf 'y'| sudo apt remove sipsak
printf 'y'| sudo apt remove sipvicious
printf 'y'| sudo apt remove skipfish
printf 'y'| sudo apt remove sleuthkit
printf 'y'| sudo apt remove slimtoolkit
printf 'y'| sudo apt remove sliver
printf 'y'| sudo apt remove slowhttptest
printf 'y'| sudo apt remove smbmap
printf 'y'| sudo apt remove smtp-user-enum
printf 'y'| sudo apt remove sn0int
printf 'y'| sudo apt remove sniffjoke
printf 'y'| sudo apt remove snmpcheck
printf 'y'| sudo apt remove snmpenum
printf 'y'| sudo apt remove snowdrop
printf 'y'| sudo apt remove socat
printf 'y'| sudo apt remove sparrow-wifi
printf 'y'| sudo apt remove spectools
printf 'y'| sudo apt remove spiderfoot
printf 'y'| sudo apt remove spike
printf 'y'| sudo apt remove spire
printf 'y'| sudo apt remove spooftooph
printf 'y'| sudo apt remove spray
printf 'y'| sudo apt remove sprayingtoolkit
printf 'y'| sudo apt remove spraykatz
printf 'y'| sudo apt remove sqldict
printf 'y'| sudo apt remove sqlitebrowser
printf 'y'| sudo apt remove sqlmap
printf 'y'| sudo apt remove sqlninja
printf 'y'| sudo apt remove sqlsus
printf 'y'| sudo apt remove ssdeep
printf 'y'| sudo apt remove ssldump
printf 'y'| sudo apt remove sslh
printf 'y'| sudo apt remove sslscan
printf 'y'| sudo apt remove sslsniff
printf 'y'| sudo apt remove sslsplit
printf 'y'| sudo apt remove sslstrip
printf 'y'| sudo apt remove sslyze
printf 'y'| sudo apt remove statsprocessor
printf 'y'| sudo apt remove stegcracker
printf 'y'| sudo apt remove steghide
printf 'y'| sudo apt remove stegsnow
printf 'y'| sudo apt remove stunnel4
printf 'y'| sudo apt remove subfinder
printf 'y'| sudo apt remove subjack
printf 'y'| sudo apt remove sublist3r
printf 'y'| sudo apt remove subversion
printf 'y'| sudo apt remove sucrack
printf 'y'| sudo apt remove sudo
printf 'y'| sudo apt remove swaks
printf 'y'| sudo apt remove syft
printf 'y'| sudo apt remove t50
printf 'y'| sudo apt remove tcpdump
printf 'y'| sudo apt remove tcpflow
printf 'y'| sudo apt remove tcpick
printf 'y'| sudo apt remove tcpreplay
printf 'y'| sudo apt remove teamsploit
printf 'y'| sudo apt remove termineter
printf 'y'| sudo apt remove terraform
printf 'y'| sudo apt remove testdisk
printf 'y'| sudo apt remove testssl.sh
printf 'y'| sudo apt remove tetragon
printf 'y'| sudo apt remove tftp-hpa
printf 'y'| sudo apt remove tftpd32
printf 'y'| sudo apt remove thc-ipv6
printf 'y'| sudo apt remove thc-pptp-bruter
printf 'y'| sudo apt remove thc-ssl-dos
printf 'y'| sudo apt remove theharvester
printf 'y'| sudo apt remove tiger
printf 'y'| sudo apt remove tightvnc
printf 'y'| sudo apt remove tlssled
printf 'y'| sudo apt remove tmux
printf 'y'| sudo apt remove tnftp
printf 'y'| sudo apt remove tnscmd10g
printf 'y'| sudo apt remove traceroute
printf 'y'| sudo apt remove trivy
printf 'y'| sudo apt remove truecrack
printf 'y'| sudo apt remove trufflehog
printf 'y'| sudo apt remove tundeep
printf 'y'| sudo apt remove twofi
printf 'y'| sudo apt remove tzdata
printf 'y'| sudo apt remove ubertooth
printf 'y'| sudo apt remove udptunnel
printf 'y'| sudo apt remove uhd
printf 'y'| sudo apt remove uhd-images
printf 'y'| sudo apt remove unar
printf 'y'| sudo apt remove unblob
printf 'y'| sudo apt remove undbx
printf 'y'| sudo apt remove unhide
printf 'y'| sudo apt remove unhide.rb
printf 'y'| sudo apt remove unicorn-magic
printf 'y'| sudo apt remove unicornscan
printf 'y'| sudo apt remove uniscan
printf 'y'| sudo apt remove unix-privesc-check
printf 'y'| sudo apt remove unrar-nonfree
printf 'y'| sudo apt remove upx-ucl
printf 'y'| sudo apt remove urlcrazy
printf 'y'| sudo apt remove util-linux
printf 'y'| sudo apt remove vboot-utils
printf 'y'| sudo apt remove veil
printf 'y'| sudo apt remove villain
printf 'y'| sudo apt remove vim
printf 'y'| sudo apt remove vinetto
printf 'y'| sudo apt remove vlan
printf 'y'| sudo apt remove voiphopper
printf 'y'| sudo apt remove vpnc
printf 'y'| sudo apt remove wafw00f
printf 'y'| sudo apt remove wapiti
printf 'y'| sudo apt remove watobo
printf 'y'| sudo apt remove wce
printf 'y'| sudo apt remove webacoo
printf 'y'| sudo apt remove webscarab
printf 'y'| sudo apt remove webshells
printf 'y'| sudo apt remove websploit
printf 'y'| sudo apt remove weevely
printf 'y'| sudo apt remove wfuzz
printf 'y'| sudo apt remove wget
printf 'y'| sudo apt remove wgetpaste
printf 'y'| sudo apt remove what-is-python
printf 'y'| sudo apt remove whatmask
printf 'y'| sudo apt remove whatweb
printf 'y'| sudo apt remove whois
printf 'y'| sudo apt remove wifi-honey
printf 'y'| sudo apt remove wifiphisher
printf 'y'| sudo apt remove wifipumpkin3
printf 'y'| sudo apt remove wifite
printf 'y'| sudo apt remove wig
printf 'y'| sudo apt remove wig-ng
printf 'y'| sudo apt remove windows-binaries
printf 'y'| sudo apt remove windows-privesc-check
printf 'y'| sudo apt remove winexe
printf 'y'| sudo apt remove winregfs
printf 'y'| sudo apt remove wireshark
printf 'y'| sudo apt remove witnessme
printf 'y'| sudo apt remove wmi
printf 'y'| sudo apt remove wordlistraider
printf 'y'| sudo apt remove wordlists
printf 'y'| sudo apt remove wotmate
printf 'y'| sudo apt remove wpa-sycophant
printf 'y'| sudo apt remove wpscan
printf 'y'| sudo apt remove wsgidav
printf 'y'| sudo apt remove xmount
printf 'y'| sudo apt remove xplico
printf 'y'| sudo apt remove xspy
printf 'y'| sudo apt remove xsser
printf 'y'| sudo apt remove yara
printf 'y'| sudo apt remove yersinia
printf 'y'| sudo apt remove zaproxy
printf 'y'| sudo apt remove zenmap-kbx
printf 'y'| sudo apt remove zerofree
printf 'y'| sudo apt remove zim
printf 'y'| sudo apt remove zonedb
printf 'y'| sudo apt remove zsh
printf 'y'| sudo apt remove zsh-autosuggestions
printf 'y'| sudo apt remove zsh-syntax-highlighting
printf 'y'| sudo apt remove maltego
printf 'y' |sudo apt remove msfpc
printf 'y' |sudo apt remove set
printf 'y' |sudo apt remove faraday
printf 'y' |sudo apt remove recordmydesktop
printf 'y' |sudo apt remove pipal
printf 'y' |sudo apt remove cutycapt
printf 'y' |sudo apt remove hashdeep
printf 'y' |sudo apt remove bulk-extractor
printf 'y' |sudo apt remove binwalk
printf 'y' |sudo apt remove autopsy
printf 'y' |sudo apt remove sleuthkit
printf 'y' |sudo apt remove pdfid
printf 'y' |sudo apt remove pdf-parser
printf 'y' |sudo apt remove forensic-artifacts
printf 'y' |sudo apt remove guymager
printf 'y' |sudo apt remove magicrescue
printf 'y' |sudo apt remove scrounge-ntfs
printf 'y' |sudo apt remove dbd
printf 'y' |sudo apt remove powersploit
printf 'y' |sudo apt remove sbd
printf 'y' |sudo apt remove dns2tcp
printf 'y' |sudo apt remove exe2hexbat
printf 'y' |sudo apt remove iodine
printf 'y' |sudo apt remove miredo
printf 'y' |sudo apt remove proxychains4
printf 'y' |sudo apt remove proxytunnel
printf 'y' |sudo apt remove ptunnel
printf 'y' |sudo apt remove pwnat
printf 'y' |sudo apt remove stunnel4
printf 'y' |sudo apt remove udptunnel
printf 'y' |sudo apt remove laudanum
printf 'y' |sudo apt remove weevely
printf 'y' |sudo apt remove dnschef
printf 'y' |sudo apt remove netsniff-ng
printf 'y' |sudo apt remove rebind
printf 'y' |sudo apt remove sslsplit
printf 'y' |sudo apt remove tcpreplay
printf 'y' |sudo apt remove ettercap-graphical
printf 'y' |sudo apt remove macchanger
printf 'y' |sudo apt remove mitmproxy
printf 'y' |sudo apt remove responder
printf 'y' |sudo apt remove wireshark
printf 'y' |sudo apt remove metasploit-framework
printf 'y' |sudo apt remove exploitdb
printf 'y' |sudo apt remove sqlmap
printf 'y' |sudo apt remove sqlitebrowser
printf 'y' |sudo apt remove bully
printf 'y' |sudo apt remove fern-wifi-cracker
printf 'y' |sudo apt remove spooftooph
printf 'y' |sudo apt remove aircrack-ng
printf 'y' |sudo apt remove kismet
printf 'y' |sudo apt remove pixiewps
printf 'y' |sudo apt remove reaver
printf 'y' |sudo apt remove wifite
printf 'y' |sudo apt remove clang
printf 'y' |sudo apt remove nasm
printf 'y' |sudo apt remove radare2
printf 'y' |sudo apt remove chntpw
printf 'y' |sudo apt remove hashcat
printf 'y' |sudo apt remove hashid
printf 'y' |sudo apt remove hash-identifier
printf 'y' |sudo apt remove ophcrack
printf 'y' |sudo apt remove ophcrack-cli
printf 'y' |sudo apt remove samdump2
printf 'y' |sudo apt remove hydra
printf 'y' |sudo apt remove hydra-gtk
printf 'y' |sudo apt remove patator
printf 'y' |sudo apt remove thc-pptp-bruter
printf 'y' |sudo apt remove passing-the-hash
printf 'y' |sudo apt remove mimikatz
printf 'y' |sudo apt remove cewl
printf 'y' |sudo apt remove crunch
printf 'y' |sudo apt remove john
printf 'y' |sudo apt remove medusa
printf 'y' |sudo apt remove ncrack
printf 'y' |sudo apt remove wordlists
printf 'y' |sudo apt remove rsmangler
printf 'y' |sudo apt remove dnsenum
printf 'y' |sudo apt remove dnsrecon
printf 'y' |sudo apt remove fierce
printf 'y' |sudo apt remove lbd
printf 'y' |sudo apt remove wafw00f
printf 'y' |sudo apt remove arping
printf 'y' |sudo apt remove fping
printf 'y' |sudo apt remove hping3
printf 'y' |sudo apt remove masscan
printf 'y' |sudo apt remove thc-ipv6
printf 'y' |sudo apt remove theharvester
printf 'y' |sudo apt remove netdiscover
printf 'y' |sudo apt remove netmask
printf 'y' |sudo apt remove enum4linux
printf 'y' |sudo apt remove nbtscan
printf 'y' |sudo apt remove smbmap
printf 'y' |sudo apt remove swaks
printf 'y' |sudo apt remove onesixtyone
printf 'y' |sudo apt remove snmpcheck
printf 'y' |sudo apt remove ssldump
printf 'y' |sudo apt remove sslh
printf 'y' |sudo apt remove sslscan
printf 'y' |sudo apt remove sslyze
printf 'y' |sudo apt remove dmitry
printf 'y' |sudo apt remove ike-scan
printf 'y' |sudo apt remove recon-ng
printf 'y' |sudo apt remove spike
printf 'y' |sudo apt remove voiphopper
printf 'y' |sudo apt remove legion
printf 'y' |sudo apt remove nikto
printf 'y' |sudo apt remove nmap
printf 'y' |sudo apt remove unix-privesc-check
printf 'y' |sudo apt remove wpscan
printf 'y' |sudo apt remove burpsuite
printf 'y' |sudo apt remove dirb
printf 'y' |sudo apt remove dirbuster
printf 'y' |sudo apt remove wfuzz
printf 'y' |sudo apt remove cadaver
printf 'y' |sudo apt remove davtest
printf 'y' |sudo apt remove skipfish
printf 'y' |sudo apt remove wapiti
printf 'y' |sudo apt remove whatweb
printf 'y' |sudo apt remove commix
printf 'y' |sudo apt remove zaproxy
printf 'y' |sudo apt remove freerdp2-x11
printf 'y' |sudo apt remove scalpel
printf 'y' |sudo apt remove spiderfoot
printf 'y' |sudo apt autoclean
printf 'y' |sudo apt autoremove
printf 'y' |sudo apt update

#To remove configurations of all removed packages, remove the hastag before the following line
#dpkg -l | grep '^rc' | awk '{print $2}' | sudo xargs dpkg --purge

echo "The script has been successfully executed"
echo "Tools has been removed/uninstalled"
echo "Thanks for using this script"
